name: Deploy Sphinx Documentation

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme  # add any other Sphinx extensions you use
          pip install -r requirements.txt
          
      - name: Build documentation
        run: |
          cd docs  # adjust if your Sphinx files are in a different directory
          make html
          
      - name: Deploy to GitHub Pages
        if: success() && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html  
          force_orphan: true  
          full_commit_message: 'Deploy documentation updates'